consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateBottlePayload:
    example:
      href: Laboriosam placeat ducimus doloribus voluptates iusto.
      name: Labore voluptatem omnis consequuntur voluptatibus odit.
    properties:
      href:
        example: Laboriosam placeat ducimus doloribus voluptates iusto.
        type: string
      name:
        example: Labore voluptatem omnis consequuntur voluptatibus odit.
        type: string
    title: CreateBottlePayload
    type: object
  GoaExampleBottle:
    description: A bottle of wine (default view)
    example:
      href: Voluptates non excepturi.
      id: 6.9965735e+18
      name: Tenetur et saepe ratione debitis enim sapiente.
    properties:
      href:
        description: API href for making requests on the bottle
        example: Voluptates non excepturi.
        type: string
      id:
        description: Unique bottle ID
        example: 6.9965735e+18
        format: int64
        type: integer
      name:
        description: Name of wine
        example: Tenetur et saepe ratione debitis enim sapiente.
        type: string
    required:
    - id
    - href
    - name
    title: 'Mediatype identifier: application/vnd.goa.example.bottle+json'
    type: object
  ListBottlePayload:
    title: ListBottlePayload
    type: object
  UpdateBottlePayload:
    example:
      href: Omnis dolorem corporis.
      name: Voluptates esse magnam ut consequatur debitis.
    properties:
      href:
        example: Omnis dolorem corporis.
        type: string
      name:
        example: Voluptates esse magnam ut consequatur debitis.
        type: string
    title: UpdateBottlePayload
    type: object
host: localhost:8080
info:
  description: A simple goa service
  title: The virtual wine cellar
  version: ""
paths:
  /bottles:
    get:
      description: list bottle
      operationId: bottle#list
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ListBottlePayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaExampleBottle'
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: list bottle
      tags:
      - bottle
    post:
      description: create a bottle
      operationId: bottle#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateBottlePayload'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      schemes:
      - http
      summary: create bottle
      tags:
      - bottle
  /bottles/{bottleID}:
    delete:
      description: delete a bottle
      operationId: bottle#delete
      parameters:
      - description: Bottle ID
        in: path
        name: bottleID
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
      schemes:
      - http
      summary: delete bottle
      tags:
      - bottle
    get:
      description: Get bottle by id
      operationId: bottle#show
      parameters:
      - description: Bottle ID
        in: path
        name: bottleID
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaExampleBottle'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show bottle
      tags:
      - bottle
    post:
      description: update a bottle
      operationId: bottle#update
      parameters:
      - in: path
        name: bottleID
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateBottlePayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaExampleBottle'
        "400":
          description: Bad Request
      schemes:
      - http
      summary: update bottle
      tags:
      - bottle
produces:
- application/json
responses:
  BadRequest:
    description: Bad Request
  Created:
    description: Created
  InternalServerError:
    description: Internal Server Error
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/GoaExampleBottle'
schemes:
- http
swagger: "2.0"
